[build]
  command = "npm install && npm install --save-dev @netlify/plugin-nextjs && npm run build"
  publish = ".next"
  functions = "functions"
  base = "/"

[build.environment]
  NODE_VERSION = "22.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_LIGHTNINGCSS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  target = "."
  command = "npm run dev"
  port = 3000
  publish = ".next"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lightningcss"]

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
